### ISSUE TITLE
Editor Download

### ISSUE THREAD

**Issue by dackdel** [GitbookIO/editor-legacy#213]
Cannot download the editor it links me to a 404 page. https://www.dropbox.com/s/11pif5xn4a0t6uk/Screenshot%202015-06-26%2017.55.35.png?dl=0

Have you discontinued the native editor? I wanted to the use native editor because I was having trouble adding plugins in the online editor.

**Comment by SamyPesse** [comment]
You can download it from here: https://github.com/GitbookIO/editor-legacy/releases
