### ISSUE TITLE
Support schedule for this 'legacy' version

### ISSUE THREAD

**Issue by designermonkey** [GitbookIO/editor-legacy#217]
I have come to use this editor as my go to when producing client documentation as it packages things up very nicely.

I've just come to re-download the dmg for a new installation and notice it's now `editor-legacy`.

Does this mean this editor is no longer supported? Can we see a support schedule for it? Or have all efforts gone over to the website? (Which isn't for me as client docs are private, and not publishable books)

**Comment by SamyPesse** [comment]
This editor is now longer supported by we have a new editor in work, we'll probably release it in the coming months.
This new editor will be more integrated with gitbook.com but will still support all other features (export, ..).

In the mid time, you can keep using this editor, you'll get an update dialog when the new editor will be released.
