### ISSUE TITLE
Do Desktop Editor will no longer maintained?

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/editor-legacy#218]
Hi Guys, 

As you're doing a great job in Gitbook project but what I see it that you guys don't fix/update the desktop version since +11 months. 

Are you going to no longer maintain this part of gitbook? 

For me I'm using it in daily bases even not for gitbook because it's good and easy to use.

Appreciated!

**Comment by iphyer** [comment]
+1

Also concerns with the problem

**Comment by SamyPesse** [comment]
Don't worry, We have a new version of the desktop editor coming soon. We are still working on some details before shipping it to gitbook.com users.

You'll be notified with a update dialog in your current editor.

**Comment by SamyPesse** [comment]
Update: https://twitter.com/gitbookio/status/636167095898800128
