### ISSUE TITLE
New Error to update books into Gitbook Website

### ISSUE THREAD

**Issue by iphyer** [GitbookIO/editor-legacy#219]
I encounter a error today,which says 

`Error:Cannot call method 'apply' of undefined`

when I use the button `Publish As `

How solve this problem?

Thank you!

PS:

Is this editor dead?
Can someone succeed the role of maintaining it? Because this is really useful especially when you dislike to write a lot in your web browser.

**Comment by SamyPesse** [comment]
We are working on fixing this error. A fix will be live soon.

This editor is no longer supported but we are working on a new editor, you'll be notified to update in your current editor, in the mid-time you can still use this editor.

**Comment by SamyPesse** [comment]
It should be fixed now :)

**Comment by iphyer** [comment]
Thank you!This is wonderful!
