### ISSUE TITLE
Feature: Spell Check

### ISSUE THREAD

**Issue by Hermanya** [GitbookIO/editor-legacy#51]
Some GitBook books suffer from typos.It would be nice, if misspelling was highlighted.

**Comment by robertriordan** [comment]
+1 yes please! for a spellchecker

**Comment by err0** [comment]
Is there plans to use [Hunspell][1] for this?  Including it in the editor?

[1]: https://github.com/GitbookIO/hunspell-spellchecker

**Comment by linkwisdom** [comment]
how to close spellchecker? it's too bad for chinese
